### ISSUE TITLE
the check to make sure not --looponfail isn't working

### ISSUE THREAD

**Issue by klrmn** [gocept/pytest-rerunfailures#1]

**Comment by florianpilz** [comment]
@klrmn What exaclty is meant by this issue? The topic alone doesn't help.

**Comment by klrmn** [comment]
i wish i remembered. i suggest you close it and wait until you / someone
else runs into whatever i thought the problem might be =). maybe i intended
for my plugin to self-disable if another plugin's --looponfail was
requested?
