### ISSUE TITLE
pytest-rerunfailures seeing skips as failures

### ISSUE THREAD

**Issue by bobsilverberg** [gocept/pytest-rerunfailures#13]
When running a test that includes a `@pytest.mark.skipif()`, when the test is skipped by pytest the plugin sees this as a failure and tries to rerun the test which is, of course, skipped again. With our Selenium tests, this causes a browser to open and then immediately close, which is unnecessary overhead (as is really any activity required to run and skip the test again).

The plugin should be updated to treat a skip as a pass so it will not be rerun.

**Comment by florianpilz** [comment]
Hi bobsilverberg! We (gocept) have accepted the ownership of pytest-rerunfailures and are the new maintainers.

The problem you are encountering should be fixed, I agree. But it looks to me as if it is the same problem as stated by Pull Request https://github.com/gocept/pytest-rerunfailures/pull/17. There is already some work going on, so feel free to finish the tests so the PR can be merged.

**Comment by florianpilz** [comment]
Was fixed by @davehunt. Before version 1.0.0 it was checked whether the test `passed`, not it is tested whether the test `failed`.
