### ISSUE TITLE
Number of times a test is reran?

### ISSUE THREAD

**Issue by keightley92** [gocept/pytest-rerunfailures#20]
Is there a way to see how many times one test was reran, i know at the end it shows how many where reran but it dosent show how many times one test was reran

**Comment by klrmn** [comment]
not in so many words, but if you use the "-r R" flag, then it will create a
list like

=========================== rerun test summary info ============================
RERUN test_report_on_with_reruns.py::test_flaky_test
RERUN test_report_on_with_reruns.py::test_flaky_test


Please note that pytest-rerunfailures is not under active development,
and I am unlikely to implement any new features.


-Leah

**Comment by florianpilz** [comment]
Hi keightley92! We (gocept) have accepted the ownership of pytest-rerunfailures and are the new maintainers.

Even though it might be nice to see a number, it does not provide a lot of value. Compared to the other issues currently opened, it is a minor problem and not worth our time atm. If you are eager to see a number, go ahead and implement it yourself. We will gladly accept tested pull requests.
